# Ghidra headless analysis script for C64 ROM - Version 3 (Simplified)

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor
from ghidra.app.cmd.disassemble import DisassembleCommand
from ghidra.app.cmd.function import CreateFunctionCmd

def analyze_c64_rom():
    """Analyze C64 ROM"""

    monitor = ConsoleTaskMonitor()

    # Start at $8000
    addr_factory = currentProgram.getAddressFactory()
    start_addr = addr_factory.getAddress("8000")

    print("=" * 60)
    print("C64 ROM ANALYSIS STARTING")
    print("=" * 60)
    print("Entry point: {}".format(start_addr))

    # Disassemble from $8000
    print("\n[1/3] Disassembling from $8000...")
    disassemble_cmd = DisassembleCommand(start_addr, None, True)
    disassemble_cmd.applyTo(currentProgram, monitor)
    print("  Disassembly complete!")

    # Create function at entry point
    print("\n[2/3] Creating function at entry point...")
    func_cmd = CreateFunctionCmd(start_addr)
    func_cmd.applyTo(currentProgram, monitor)
    print("  Function created!")

    # Export decompiled code
    print("\n[3/3] Decompiling functions...")
    decompiler = DecompInterface()
    decompiler.openProgram(currentProgram)

    output_lines = []
    output_lines.append("// C64 ROM Bank 00 - Decompiled Code")
    output_lines.append("// Overlord (Supremacy) - Commodore 64 Version")
    output_lines.append("// EasyFlash Cartridge Bank 0, Load Address: $8000")
    output_lines.append("//")
    output_lines.append("// Generated by Ghidra " + str(getGhidraVersion()))
    output_lines.append("")
    output_lines.append("typedef unsigned char byte;")
    output_lines.append("typedef unsigned short word;")
    output_lines.append("")
    output_lines.append("// C64 Memory-Mapped I/O Registers")
    output_lines.append("// $D000-$D3FF: VIC-II (graphics)")
    output_lines.append("// $D400-$D7FF: SID (sound)")
    output_lines.append("// $DC00-$DCFF: CIA #1 (keyboard, joystick)")
    output_lines.append("// $DD00-$DDFF: CIA #2 (serial, timers)")
    output_lines.append("// $DE00-$DEFF: EasyFlash registers (bank switching)")
    output_lines.append("")

    # Get all functions
    fm = currentProgram.getFunctionManager()
    functions = list(fm.getFunctions(True))

    print("  Found {} function(s)".format(len(functions)))

    func_count = 0
    for func in functions:
        func_count += 1
        func_name = func.getName()
        func_addr = func.getEntryPoint()

        print("    [{}/{}] Decompiling: {} at {}".format(func_count, len(functions), func_name, func_addr))

        # Decompile
        results = decompiler.decompileFunction(func, 60, monitor)

        if results and results.decompileCompleted():
            decomp_code = results.getDecompiledFunction()
            c_code = decomp_code.getC()

            output_lines.append("")
            output_lines.append("// " + "=" * 70)
            output_lines.append("// Function: {}".format(func_name))
            output_lines.append("// Address: {}".format(func_addr))
            output_lines.append("// " + "=" * 70)
            output_lines.append(c_code)
        else:
            output_lines.append("")
            output_lines.append("// ERROR: Failed to decompile {}".format(func_name))

    # Also add raw disassembly sample
    output_lines.append("")
    output_lines.append("")
    output_lines.append("/* " + "=" * 70)
    output_lines.append("   RAW DISASSEMBLY - First 200 instructions from $8000")
    output_lines.append("   " + "=" * 70 + " */")
    output_lines.append("/*")

    listing = currentProgram.getListing()
    addr = start_addr
    for i in range(200):
        cu = listing.getCodeUnitAt(addr)
        if cu:
            output_lines.append("{:04x}:  {}".format(addr.getOffset(), cu))
            next_addr = cu.getMaxAddress().add(1)
            if next_addr.compareTo(addr) <= 0:  # Safety check
                break
            addr = next_addr
        else:
            break

    output_lines.append("*/")

    # Write output file
    output_file = "C:/dev/GIT/Overlord/analysis/c64/bank_00_headless.c"
    full_output = '\n'.join(output_lines)

    f = open(output_file, 'w')
    f.write(full_output)
    f.close()

    print("")
    print("=" * 60)
    print("ANALYSIS COMPLETE!")
    print("=" * 60)
    print("Functions decompiled: {}".format(len(functions)))
    print("Output file: {}".format(output_file))
    print("File size: {:,} bytes".format(len(full_output)))
    print("=" * 60)

# Run
analyze_c64_rom()
