# Ghidra headless analysis script for C64 ROM - Version 2
# Force disassembly and function creation

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor
from ghidra.program.model.listing import CodeUnit
from ghidra.program.model.address import Address
from ghidra.program.model.symbol import SourceType

def analyze_c64_rom():
    """Analyze C64 ROM by forcing disassembly and function creation"""

    monitor = ConsoleTaskMonitor()

    # Get address factory
    addr_factory = currentProgram.getAddressFactory()
    default_space = addr_factory.getDefaultAddressSpace()

    # Start at $8000 (cartridge entry point)
    start_addr = addr_factory.getAddress("8000")

    print("Starting C64 ROM analysis at address: {}".format(start_addr))

    # Get the disassembler
    from ghidra.app.cmd.disassemble import DisassembleCommand

    # Disassemble from $8000
    print("Disassembling from $8000...")
    disassemble_cmd = DisassembleCommand(start_addr, None, True)
    disassemble_cmd.applyTo(currentProgram, monitor)

    # Create function at entry point
    print("Creating function at entry point...")
    from ghidra.app.cmd.function import CreateFunctionCmd
    func_cmd = CreateFunctionCmd(start_addr)
    func_cmd.applyTo(currentProgram, monitor)

    # Run auto-analysis again
    print("Running auto-analysis...")
    from ghidra.program.util import GhidraProgramUtilities
    from ghidra.app.script import GhidraScriptUtil
    from ghidra.app.services import AutoAnalysisManager

    analysismgr = AutoAnalysisManager.getAnalysisManager(currentProgram)
    analysismgr.reAnalyzeAll(None)
    analysismgr.waitForAnalysis(None, monitor)

    print("Analysis complete!")

    # Now export decompiled code
    decompiler = DecompInterface()
    decompiler.openProgram(currentProgram)

    output_lines = []
    output_lines.append("// C64 ROM Bank 00 Decompiled Code")
    output_lines.append("// Generated by Ghidra - Forced Analysis")
    output_lines.append("")
    output_lines.append("typedef unsigned char byte;")
    output_lines.append("typedef unsigned short word;")
    output_lines.append("")

    # Get all functions
    fm = currentProgram.getFunctionManager()
    functions = list(fm.getFunctions(True))

    print("Found {} functions".format(len(functions)))

    for func in functions:
        print("Decompiling: {} at {}".format(func.getName(), func.getEntryPoint()))

        # Decompile the function
        results = decompiler.decompileFunction(func, 30, monitor)

        if results and results.decompileCompleted():
            # Get the C code
            decomp_code = results.getDecompiledFunction()
            c_code = decomp_code.getC()

            output_lines.append("")
            output_lines.append("// ===== Function: {} =====".format(func.getName()))
            output_lines.append("// Address: {}".format(func.getEntryPoint()))
            output_lines.append(c_code)
        else:
            output_lines.append("")
            output_lines.append("// FAILED to decompile: {}".format(func.getName()))

    # Also dump some raw disassembly
    output_lines.append("")
    output_lines.append("")
    output_lines.append("/* ===== RAW DISASSEMBLY (first 256 bytes) ===== */")
    output_lines.append("/*")

    listing = currentProgram.getListing()
    addr = start_addr
    for i in range(100):  # Get first 100 instructions
        cu = listing.getCodeUnitAt(addr)
        if cu:
            output_lines.append("{}:  {}".format(addr, cu))
            addr = cu.getMaxAddress().add(1)
        else:
            break

    output_lines.append("*/")

    # Write to file
    output_file = "C:/dev/GIT/Overlord/analysis/c64/bank_00_headless.c"
    f = open(output_file, 'w')
    f.write('\n'.join(output_lines))
    f.close()

    print("")
    print("=" * 60)
    print("RESULTS:")
    print("  Functions found: {}".format(len(functions)))
    print("  Output file: {}".format(output_file))
    print("  File size: {} bytes".format(len('\n'.join(output_lines))))
    print("=" * 60)

# Run the analysis
analyze_c64_rom()
