# Ghidra headless analysis script for C64 ROM
# This script will be run by Ghidra's headless analyzer

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor

def export_decompiled_code():
    """Export all decompiled functions to a C file"""

    monitor = ConsoleTaskMonitor()
    decompiler = DecompInterface()
    decompiler.openProgram(currentProgram)

    output_lines = []
    output_lines.append("// C64 ROM Bank 00 Decompiled Code")
    output_lines.append("// Generated by Ghidra")
    output_lines.append("")
    output_lines.append("typedef unsigned char byte;")
    output_lines.append("typedef unsigned short word;")
    output_lines.append("")

    # Get all functions
    fm = currentProgram.getFunctionManager()
    functions = fm.getFunctions(True)

    func_count = 0
    for func in functions:
        func_count += 1
        print("Decompiling function: {} at {}".format(func.getName(), func.getEntryPoint()))

        # Decompile the function
        results = decompiler.decompileFunction(func, 30, monitor)

        if results and results.decompileCompleted():
            # Get the C code
            decomp_code = results.getDecompiledFunction()
            c_code = decomp_code.getC()

            output_lines.append("")
            output_lines.append("// Address: {}".format(func.getEntryPoint()))
            output_lines.append(c_code)
        else:
            output_lines.append("")
            output_lines.append("// Failed to decompile: {}".format(func.getName()))

    print("Total functions decompiled: {}".format(func_count))

    # Write to file
    output_file = "C:/dev/GIT/Overlord/analysis/c64/bank_00_headless.c"
    f = open(output_file, 'w')
    f.write('\n'.join(output_lines))
    f.close()

    print("Decompiled code written to: {}".format(output_file))
    print("File size: {} bytes".format(len('\n'.join(output_lines))))

# Run the export
export_decompiled_code()
