// C64 ROM Bank 00 - Decompiled Code
// Overlord (Supremacy) - Commodore 64 Version
// EasyFlash Cartridge Bank 0, Load Address: $8000
//
// Generated by Ghidra 11.4.3

typedef unsigned char byte;
typedef unsigned short word;

// C64 Memory-Mapped I/O Registers
// $D000-$D3FF: VIC-II (graphics)
// $D400-$D7FF: SID (sound)
// $DC00-$DCFF: CIA #1 (keyboard, joystick)
// $DD00-$DDFF: CIA #2 (serial, timers)
// $DE00-$DEFF: EasyFlash registers (bank switching)


// ======================================================================
// Function: FUN_8000
// Address: 8000
// ======================================================================

/* WARNING: Control flow encountered bad instruction data */

void FUN_8000(void)

{
  byte bVar1;
  
  DAT_0318 = 0xc1;
  NMI = 0x26;
  DAT_fffb = 200;
  bVar1 = 0xf;
  do {
    *(undefined1 *)(bVar1 + 0x100) = 0;
    bVar1 = bVar1 - 1;
  } while (-1 < (char)bVar1);
  func_0x835b();
  bVar1 = 0;
  do {
    (&LAB_c800)[bVar1] = *(undefined1 *)(bVar1 + 0x8076);
    bVar1 = bVar1 + 1;
  } while (bVar1 != 0xe5);
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}




/* ======================================================================
   RAW DISASSEMBLY - First 200 instructions from $8000
   ====================================================================== */
/*
8000:  LDA #0xc1
8002:  STA 0x0318
8005:  LDA #0x26
8007:  STA 0xfffa
800a:  LDA #0xc8
800c:  STA 0xfffb
800f:  LDX #0xf
8011:  LDA #0x0
8013:  STA 0x100,X
8016:  DEX
8017:  BPL 0x8013
8019:  JSR 0x835b
801c:  LDX #0x0
801e:  LDA 0x8076,X
8021:  STA 0xc800,X
8024:  INX
8025:  CPX #0xe5
8027:  BNE 0x801e
8029:  JMP 0xc800
802c:  ?? 45h    E
802d:  ?? 58h    X
802e:  ?? 43h    C
802f:  ?? 45h    E
8030:  ?? 53h    S
8031:  ?? 53h    S
8032:  ?? 20h     
8033:  ?? 45h    E
8034:  ?? 41h    A
8035:  ?? 53h    S
8036:  ?? 59h    Y
8037:  ?? 46h    F
8038:  ?? 4Ch    L
8039:  ?? 41h    A
803a:  ?? 53h    S
803b:  ?? 48h    H
803c:  ?? 20h     
803d:  ?? 4Ch    L
803e:  ?? 4Fh    O
803f:  ?? 41h    A
8040:  ?? 44h    D
8041:  ?? 45h    E
8042:  ?? 52h    R
8043:  ?? 20h     
8044:  ?? 3Ah    :
8045:  ?? 20h     
8046:  ?? 4Dh    M
8047:  ?? 4Fh    O
8048:  ?? 52h    R
8049:  ?? 45h    E
804a:  ?? 20h     
804b:  ?? 54h    T
804c:  ?? 48h    H
804d:  ?? 41h    A
804e:  ?? 4Eh    N
804f:  ?? 20h     
8050:  ?? 59h    Y
8051:  ?? 4Fh    O
8052:  ?? 55h    U
8053:  ?? 20h     
8054:  ?? 44h    D
8055:  ?? 45h    E
8056:  ?? 53h    S
8057:  ?? 45h    E
8058:  ?? 52h    R
8059:  ?? 56h    V
805a:  ?? 45h    E
805b:  ?? A0h
805c:  ?? 00h
805d:  ?? B9h
805e:  ?? 00h
805f:  ?? B8h
8060:  ?? 99h
8061:  ?? 00h
8062:  ?? CCh
8063:  ?? B9h
8064:  ?? 00h
8065:  ?? B9h
8066:  ?? 99h
8067:  ?? 00h
8068:  ?? CDh
8069:  ?? B9h
806a:  ?? 00h
806b:  ?? BAh
806c:  ?? 99h
806d:  ?? 00h
806e:  ?? CEh
806f:  ?? C8h
8070:  ?? D0h
8071:  ?? EBh
8072:  ?? 20h     
8073:  ?? 14h
8074:  ?? CCh
8075:  ?? 60h    `
8076:  ?? A6h
8077:  ?? 02h
8078:  ?? 20h     
8079:  ?? 16h
807a:  ?? C8h
807b:  ?? 20h     
807c:  ?? 00h
807d:  ?? 82h
807e:  ?? 20h     
807f:  ?? 4Fh    O
8080:  ?? C8h
8081:  ?? E8h
8082:  ?? E0h
8083:  ?? 04h
8084:  ?? D0h
8085:  ?? F2h
8086:  ?? 20h     
8087:  ?? 16h
8088:  ?? C8h
8089:  ?? 4Ch    L
808a:  ?? 00h
808b:  ?? 80h
808c:  ?? 78h    x
808d:  ?? A9h
808e:  ?? 37h    7
808f:  ?? 85h
8090:  ?? 01h
8091:  ?? A9h
8092:  ?? 87h
8093:  ?? 8Dh
8094:  ?? 02h
8095:  ?? DEh
8096:  ?? A9h
8097:  ?? 00h
8098:  ?? 8Dh
8099:  ?? 00h
809a:  ?? DEh
809b:  ?? 60h    `
809c:  ?? 40h    @
809d:  ?? 1Dh
809e:  ?? 1Dh
809f:  ?? 1Dh
80a0:  ?? 1Dh
80a1:  ?? 02h
80a2:  ?? 23h    #
80a3:  ?? 02h
80a4:  ?? 02h
80a5:  ?? 80h
80a6:  ?? ACh
80a7:  ?? B4h
80a8:  ?? B8h
80a9:  ?? 00h
80aa:  ?? 21h    !
80ab:  ?? 00h
80ac:  ?? 00h
80ad:  ?? 80h
80ae:  ?? ACh
80af:  ?? B4h
80b0:  ?? B8h
80b1:  ?? 1Fh
80b2:  ?? F4h
80b3:  ?? E9h
80b4:  ?? EAh
80b5:  ?? 2Ch    ,
80b6:  ?? 06h
80b7:  ?? 03h
80b8:  ?? 43h    C
80b9:  ?? 00h
80ba:  ?? 00h
80bb:  ?? 5Dh    ]
80bc:  ?? 0Dh
80bd:  ?? 3Ch    <
80be:  ?? 0Ch
80bf:  ?? 05h
80c0:  ?? 08h
80c1:  ?? 00h
80c2:  ?? 00h
80c3:  ?? 01h
80c4:  ?? 00h
80c5:  ?? 8Ah
80c6:  ?? 48h    H
80c7:  ?? A6h
80c8:  ?? E0h
80c9:  ?? 8Eh
80ca:  ?? 00h
80cb:  ?? DEh
80cc:  ?? A9h
80cd:  ?? 33h    3
80ce:  ?? 85h
80cf:  ?? 01h
80d0:  ?? A5h
80d1:  ?? E4h
80d2:  ?? 8Dh
80d3:  ?? 8Ah
80d4:  ?? C8h
80d5:  ?? A5h
80d6:  ?? E5h
80d7:  ?? 8Dh
80d8:  ?? 8Bh
80d9:  ?? C8h
80da:  ?? A0h
80db:  ?? 01h
80dc:  ?? B1h
80dd:  ?? ECh
80de:  ?? 8Dh
80df:  ?? AEh
80e0:  ?? C8h
*/